on: [push, pull_request]

name: monorepo

jobs:
  do-de-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: ./node_modules/.bin/lerna run lint
      - run: ./node_modules/.bin/lerna run test -- --coverage
      - name: Coveralls (signpdf)
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: signpdf
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/signpdf
          path-to-lcov: packages/signpdf/coverage/lcov.info
      - name: Coveralls (utils)
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: utils
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/utils
          path-to-lcov: packages/utils/coverage/lcov.info
      - name: Coveralls (placeholder-pdfkit010)
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: placeholder-pdfkit010
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/placeholder-pdfkit010
          path-to-lcov: packages/placeholder-pdfkit010/coverage/lcov.info
      - name: Coveralls (placeholder-pdfkit)
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: placeholder-pdfkit
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/placeholder-pdfkit
          path-to-lcov: packages/placeholder-pdfkit/coverage/lcov.info
      - name: Coveralls (placeholder-plain)
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: placeholder-plain
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/placeholder-plain
          path-to-lcov: packages/placeholder-plain/coverage/lcov.info
      - name: Coveralls (placeholder-pdf-lib)
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: placeholder-pdf-lib
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/placeholder-pdf-lib
          path-to-lcov: packages/placeholder-pdf-lib/coverage/lcov.info
      - name: Close Coveralls
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@master
        with:
          parallel-finished: true
          carryforward: "signpdf,utils,placeholder-pdfkit010,placeholder-pdfkit,placeholder-plain"
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: ./node_modules/.bin/lerna run test
